### PR TITLE
[Merged by Bors] - ci: add old e2e tests (IN-000)

### PR DESCRIPTION
**Pull request by Xavientois**
### Brief description. What is this change?

Add back old e2e tests until new ones are stable

### CODE REVIEW

**Comment by Xavientois** [comment]
bors try

**Comment by Xavientois** [comment]
bors try

**Comment by Xavientois** [comment]
bors try

**Comment by Xavientois** [comment]
bors try

**Comment by Xavientois** [comment]
bors try

**Comment by Xavientois** [comment]
bors try

**Comment by Xavientois** [comment]
bors try

**Review by xavidop — APPROVED** [review]

**Comment by Xavientois** [comment]
bors merge

**Pull request closed without merging**
