### PR TITLE
[Merged by Bors] - build: volta, node v20, yarn3 (PL-668)

### PR DESCRIPTION
**Pull request by theProf**
**Fixes or implements PL-668**

### Brief description. What is this change?

upgrade repo to use volta, yarn v3, node v20

### Deployment Notes

Updated circleci to use node v20 in tests and build contexts

### Related PRs

- https://github.com/voiceflow/general-runtime/pull/645

### Checklist
- [x] manual testing
- [x] run automated test suite now that it exists

### CODE REVIEW

**Review by trs — APPROVED** [review]

**Comment by theProf** [comment]
bors try

**Pull request closed without merging**
