### PR TITLE
feat: add kubernetes events to logs (IN-1271)

### PR DESCRIPTION
**Pull request by edison-vflow**
### Fixes or implements 
* Linear [ticket](https://linear.app/voiceflow/issue/IN-1271/add-events-to-e2e-logs) 

### Brief description. What is this change?
* Include kubernetes events in the e2e gathered logs 

### Related PRs
* https://github.com/voiceflow/orb-common/pull/264
* https://github.com/voiceflow/infrastructure/pull/704

- [ ] Tested in a PR

### CODE REVIEW

**Comment by edison-vflow** [comment]
bors try

**Comment by edison-vflow** [comment]
bors try

**Comment by edison-vflow** [comment]
bors try

**Comment by edison-vflow** [comment]
bors try

**Comment by edison-vflow** [comment]
bors try

**Comment by edison-vflow** [comment]
bors try

**Review by theProf — APPROVED** [review]

**Review by junydania — APPROVED** [review]

**Pull request merged**
