### PR TITLE
[Merged by Bors] - fix: bump typescript (RUN-40)

### PR DESCRIPTION
**Pull request by DecathectZero**
Nothing blew up here, and if the `bors try` passes I think it's pretty safe overall.

The build was fine.

### CODE REVIEW

**Comment by DecathectZero** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/voiceflow/general-runtime/939?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#939** <a href="https://app.graphite.dev/github/pr/voiceflow/general-runtime/939?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#937** <a href="https://app.graphite.dev/github/pr/voiceflow/general-runtime/937?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @DecathectZero and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by DecathectZero** [comment]
bors try

**Review by trs — APPROVED** [review]
Scary, that's a lotta versions lol

**Pull request closed without merging**
