### PR TITLE
[Merged by Bors] - ci: run smoke tests instead of e2e (DX-993)

### PR DESCRIPTION
**Pull request by effervescentia**
**Fixes or implements DX-993**

### Brief description. What is this change?

Run smoke test suite instead of E2E tests

### Checklist

- [ ] Breaking changes have been communicated, including:
    - New required environment variables
    - Renaming of interfaces (API routes, request/response interface, etc)
- [ ] New environment variables have [been deployed](https://www.notion.so/voiceflow/Add-Environment-Variables-be1b0136479f45f1adece7995a7adbfb)
- [ ] Appropriate tests have been written
    - Bug fixes are accompanied by an updated or new test
    - New features are accompanied by a new test

### CODE REVIEW

**Comment by effervescentia** [comment]
bors try

**Review by xavidop — APPROVED** [review]

**Comment by effervescentia** [comment]
bors retry

**Pull request closed without merging**
