### PR TITLE
fix: add alexa no reply on interaction handler (BUG-453)

### PR DESCRIPTION
**Pull request by pmvrmc**
**Fixes or implements BUG-453**

### Brief description. What is this change?
On interaction calls the no reply prompt was not being sent to the adapter/alexa.

Very similar to what we did on the captureV2 handler, there is a tiny specific logic on the interaction handler to account for this.

### CODE REVIEW

**Review by zhihil — APPROVED** [review]
The code looks good, however, I'm not able to test because the bug seem to be only reproducible on Alexa and I didn't bring my Alexa device to the office.

**Review by trs — APPROVED** [review]

**Pull request merged**
