### PR TITLE
[Merged by Bors] - fix: do not load kb for project [bugfix] (BUG-1172)

### PR DESCRIPTION
**Pull request by DecathectZero**
Testing across the following areas.

Works for KB base preview 
Screenshot 2024-03-07 at 5 24 57 PM

Works for KB preview in step
Screenshot 2024-03-07 at 5 27 15 PM

Works for prototype KB step
Screenshot 2024-03-07 at 5 28 00 PM

Works for KB Query API
Screenshot 2024-03-07 at 5 31 56 PM

KB No Match Fallback With KB
Screenshot 2024-03-07 at 5 31 56 PM
KB No Match Fallback Without KB
Screenshot 2024-03-07 at 5 54 17 PM
Screenshot 2024-03-07 at 5 54 26 PM

Fetching Version Publishing
Screenshot 2024-03-07 at 5 55 58 PM

### CODE REVIEW

**Comment by DecathectZero** [comment]
bors try

**Review by edison-vflow — APPROVED** [review]

**Pull request closed without merging**
