### PR TITLE
[Merged by Bors] - feat: add support for arm (IN-000)

### PR DESCRIPTION
**Pull request by xavidop**
**Fixes or implements VF-XXX**

### Brief description. What is this change?

support for ARM

### Checklist

- [ ] Breaking changes have been communicated, including:
    - New required environment variables
    - Renaming of interfaces (API routes, request/response interface, etc)
- [ ] New environment variables have [been deployed](https://www.notion.so/voiceflow/Add-Environment-Variables-be1b0136479f45f1adece7995a7adbfb)
- [ ] Appropriate tests have been written
    - Bug fixes are accompanied by an updated or new test
    - New features are accompanied by a new test

### CODE REVIEW

**Review by junydania — APPROVED** [review]

**Review by edison-vflow — APPROVED** [review]

**Comment by xavidop** [comment]
bors try

**Pull request closed without merging**
