### PR TITLE
[Merged by Bors] - feat: docker integration tests (PL-000)

### PR DESCRIPTION
**Pull request by theProf**
**Fixes or implements VF-XXX**

### Brief description. What is this change?

Run integration tests using orb-common docker command

### Related PRs

- https://github.com/voiceflow/orb-common/pull/202
- https://github.com/voiceflow/orb-common/pull/203

### CODE REVIEW

**Review by trs — APPROVED** [review]

**Review by xavidop — CHANGES_REQUESTED** [review]
sent some comments by slack

**Review by xavidop — APPROVED** [review]

**Comment by theProf** [comment]
bors try

**Comment by theProf** [comment]
bors try

**Comment by DecathectZero** [comment]
bors try

**Comment by theProf** [comment]
bors try

**Comment by theProf** [comment]
bors try

**Comment by theProf** [comment]
bors try

**Comment by theProf** [comment]
bors try

**Review by DecathectZero — APPROVED** [review]

**Pull request closed without merging**
